# netlify.toml - Versiune Finală pentru Deploy prin Git
# Setările de build sunt acum în interfața Netlify, deci nu le mai punem aici.

# Regula #1: API-uri
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Regula #2: Link-uri de download
[[redirects]]
  from = "/d/*"
  to = "/.netlify/functions/get-link/:splat"
  status = 200
  
# Regula #3: Protecția pentru pagina de admin
[[redirects]]
  from = "/admin.html"
  to = "/index.html"
  status = 302
  force = true
  conditions = {Role = ["!*"]}